# Generated by Django 5.1.1 on 2024-10-11 22:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DechetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_activite', models.CharField(choices=[('COLLECTE', 'Collecte'), ('TRAITEMENT', 'Traitement'), ('RECYCLAGE', 'Recyclage')], max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(help_text='Quantité en tonnes')),
                ('date_dechet', models.DateTimeField()),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type_dechet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dechettype')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dechets', to='base.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Municipalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('zone_geographique', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipalite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtatCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('date_derniere_collecte', models.DateTimeField()),
                ('prochaine_collecte_prevue', models.DateTimeField()),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_collecte', to='base.municipalite')),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citoyen', to=settings.AUTH_USER_MODEL)),
                ('municipalite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens', to='base.municipalite')),
            ],
        ),
        migrations.CreateModel(
            name='PointCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('jours_operation', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=100)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_collecte', to='base.municipalite')),
                ('types_dechets', models.ManyToManyField(to='base.dechettype')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('COLLECTE', 'Collecte'), ('TRAITEMENT', 'Traitement'), ('RECYCLAGE', 'Recyclage')], max_length=20)),
                ('quantite', models.FloatField(help_text='Quantité en tonnes')),
                ('date_operation', models.DateTimeField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='base.entreprise')),
                ('type_dechet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dechettype')),
                ('point_collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pointcollecte')),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=200)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='base.citoyen')),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to='base.municipalite')),
                ('type_dechet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='base.dechettype')),
            ],
        ),
    ]
