# Generated by Django 5.1.1 on 2024-10-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_citoyen_localisation_alter_dechet_localisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citoyen',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='citoyen',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='municipalite',
            name='nom',
        ),
    ]
