# Generated by Django 5.1.1 on 2024-10-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_citoyen_nom_remove_citoyen_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalite',
            name='region',
            field=models.CharField(choices=[('BOUCLE DU MOUHOUN', 'boucle du mouhoun'), ('CASCADES', 'cascades'), ('CENTRE', 'centre'), ('CENTRE-EST', 'centre-est'), ('CENTRE-NORD', 'centre-nord'), ('CENTRE-OUEST', 'centre-ouest'), ('CENTRE-SUD', 'centre-sud'), ('EST', 'est'), ('HAUTS-BASSINS', 'hauts-bassins'), ('NORD', 'nord'), ('PLATEAU-CENTRAL', 'plateau-central'), ('SAHEL', 'sahel'), ('SUD-OUEST', 'sud-ouest')], max_length=100, unique=True),
        ),
    ]
