# Generated by Django 5.1.1 on 2024-10-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_municipalite_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalite',
            name='zone_geographique',
        ),
    ]
