# Generated by Django 5.1.1 on 2024-10-13 21:16

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_municipalite_zone_geographique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dechettype',
            name='nom',
            field=models.CharField(choices=[('PLASTIQUE', 'Plastique'), ('PAPIER_CARTON', 'Papier/Carton'), ('VERRE', 'Verre'), ('METAL', 'Métal'), ('DECHET_ORGANIQUE', 'Déchet organique'), ('DECHET_ELECTRONIQUE', 'Déchet électronique'), ('TEXTILE', 'Textile'), ('BOIS', 'Bois'), ('PILE_BATTERIE', 'Piles/Batteries'), ('DECHET_MEDICAL', 'Déchet médical'), ('DECHET_DANGEREUX', 'Déchet dangereux'), ('AUTRE', 'Autre'), ('INCONNU', 'Inconnu'), ('NON_DEFINI', 'Non défini')], max_length=100),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='date_resolution',
            field=models.DateTimeField(blank=True, default=base.models.timeresolution, null=True),
        ),
    ]
