# Generated by Django 5.1.1 on 2024-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dechettype_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalite',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
